import AppKit
import CoreGraphics
import Vision

/// Subject and person selection, through Apple's Vision framework.
///
/// `research/masking.md` §5. `VNGenerateForegroundInstanceMaskRequest` is
/// class-agnostic subject lifting and `VNGeneratePersonSegmentationRequest`
/// gives a person matte; both are macOS 14+, which is Orion's floor, both run
/// on device, and neither adds a dependency or a licence question. The section
/// is explicit that sky is *not* available this way — those mattes are produced
/// at capture time and embedded in the file, so they cannot be generated by
/// analysing an imported raw.
///
/// ## Where the picture Vision sees comes from
///
/// These models were trained on ordinary display-referred photographs, so they
/// need one — not the scene-linear Rec.2020 the mask is applied in.
///
/// ⚠ **The tone map is not duplicated to get one.** The obvious route is a
/// second node that tone-maps the pre-geometry image, and that is a second copy
/// of the display transform: this codebase has been bitten by duplicated
/// transforms before and the two always drift. Instead the *existing* render is
/// read back — already AgX-mapped, already eight bits — taken with the crop
/// reset, the straighten at zero and the user's rotation at zero.
///
/// That leaves exactly one difference between what Vision saw and the frame
/// coordinates kind 4 requires: the camera's own EXIF quarter turn, which is an
/// exact permutation of pixels and needs no resampling. `MatteGeometry` undoes
/// it, and `orion-viewport-tests` pins it against the same sentence
/// `mask::toFrame` is derived from.
///
/// Neutralising the geometry rather than correcting for it is the other half of
/// the argument: a crop would leave the matte with no data outside the crop
/// rectangle, and a straighten would need a resample.
///
/// ## What is deliberately not done
///
/// **The matte is not regenerated when an edit changes.** Exposure and white
/// balance change what Vision would see, but they do not move the subject, and
/// regenerating means two renders plus an inference. It is generated on demand
/// and kept until the photographer asks again — the smallest rule that is
/// correct, at the cost of a matte that was computed under an older grade.
@MainActor
enum SubjectMatte {

    enum Kind {
        case subject
        case person

        var label: String { self == .subject ? "Subject" : "Person" }
    }

    enum Failure: LocalizedError {
        case noPhoto
        case couldNotRender
        case nothingFound
        case vision(String)

        var errorDescription: String? {
            switch self {
            case .noPhoto:         return "No photo is open."
            case .couldNotRender:  return "Could not read the rendered picture."
            case .nothingFound:
                return "Nothing was found to select in this photograph."
            case .vision(let m):   return "Vision could not analyse this photo: \(m)"
            }
        }
    }

    /// Long edge handed to the model. See `MatteGeometry.previewSize` for why
    /// more than this buys nothing.
    static let previewLongEdge = 1024

    /// Produces a matte for the open photo, in **frame** coordinates.
    ///
    /// The render and the readback happen on the main actor because they touch
    /// the engine; the inference does not, and is the part worth getting off it.
    static func generate(engine: Engine, kind: Kind) async throws
        -> (alpha: [Float], width: Int, height: Int) {

        guard engine.isLoaded else { throw Failure.noPhoto }

        let turns = engine.quarterTurns
        guard let image = engine.renderForAnalysis(longEdge: previewLongEdge) else {
            throw Failure.couldNotRender
        }

        let w = image.width, h = image.height
        let screenSpace = try await Task.detached(priority: .userInitiated) {
            try infer(image, kind: kind, width: w, height: h)
        }.value

        // Back into frame coordinates. The only thing left between the two is
        // the EXIF turn, because `renderForAnalysis` neutralised the rest.
        let framed = MatteGeometry.undoTurns(screenSpace, width: w, height: h,
                                             turns: turns)
        return (framed.pixels, framed.width, framed.height)
    }

    /// The same thing, without the actor hop.
    ///
    /// For the scenario runner, which has no run loop turning and so cannot
    /// await. ⚠ It exists so the feature is *exercised* rather than shipped on
    /// the strength of it compiling — Vision's own output cannot be asserted,
    /// but "it ran, it returned coverage, and the coverage reached the picture"
    /// can be, and was not checkable at all without this.
    static func generateBlocking(engine: Engine, kind: Kind) throws
        -> (alpha: [Float], width: Int, height: Int) {

        guard engine.isLoaded else { throw Failure.noPhoto }
        let turns = engine.quarterTurns
        guard let image = engine.renderForAnalysis(longEdge: previewLongEdge) else {
            throw Failure.couldNotRender
        }
        let screenSpace = try infer(image, kind: kind,
                                    width: image.width, height: image.height)
        let framed = MatteGeometry.undoTurns(screenSpace, width: image.width,
                                             height: image.height, turns: turns)
        return (framed.pixels, framed.width, framed.height)
    }

    // MARK: The inference

    private nonisolated static func infer(_ image: CGImage, kind: Kind,
                                          width: Int, height: Int) throws -> [Float] {
        do {
            let handler = VNImageRequestHandler(cgImage: image, options: [:])
            let buffer: CVPixelBuffer

            switch kind {
            case .subject:
                let request = VNGenerateForegroundInstanceMaskRequest()
                do { try handler.perform([request]) }
                catch { throw Failure.vision(error.localizedDescription) }

                // `allInstances` is empty when the model found no subject. That
                // is a real answer, not an error, and it has to be said out loud
                // — a silently empty matte reads as "the feature is broken".
                guard let observation = request.results?.first,
                      !observation.allInstances.isEmpty else {
                    throw Failure.nothingFound
                }
                do {
                    buffer = try observation.generateScaledMaskForImage(
                        forInstances: observation.allInstances, from: handler)
                } catch {
                    throw Failure.vision(error.localizedDescription)
                }

            case .person:
                let request = VNGeneratePersonSegmentationRequest()
                // Accurate rather than fast: this runs once, on demand, off the
                // main actor, and the whole point of it is the boundary.
                request.qualityLevel = .accurate
                request.outputPixelFormat = kCVPixelFormatType_OneComponent8
                do { try handler.perform([request]) }
                catch { throw Failure.vision(error.localizedDescription) }

                guard let observation = request.results?.first else {
                    throw Failure.nothingFound
                }
                buffer = observation.pixelBuffer
            }

            let alpha = try floats(from: buffer, width: width, height: height)

            // ⚠ Found by running it, not by reading it. The person request does
            // not report "no people" by returning no observation — it returns
            // an observation whose mask is entirely zero, so the guard above
            // never fires and an empty selection would be uploaded in silence.
            // On a forecourt with no people in it that is exactly what
            // happened: no error, no coverage, and nothing to distinguish the
            // model declining from the feature being broken.
            //
            // The threshold is a pixel count rather than a sum, because a
            // handful of stray low-confidence pixels is also nothing anyone
            // asked to select.
            var lit = 0
            for v in alpha where v > 0.5 { lit += 1 }
            guard lit * 200 >= alpha.count else { throw Failure.nothingFound }
            return alpha
        }
    }

    /// A Vision mask buffer as coverage, resampled to the preview's own grid.
    ///
    /// ⚠ Vision returns the mask at the model's resolution, which is **not**
    /// the input's — `generateScaledMaskForImage` scales to the image but the
    /// person request does not, and assuming either would silently stretch the
    /// matte across the frame. The buffer's own dimensions are read and mapped,
    /// nearest-neighbour: the boundary here is coarse by construction and the
    /// guided refinement is what recovers it, so a smoother resample would only
    /// be inventing detail before the filter that exists to do that.
    private nonisolated static func floats(from buffer: CVPixelBuffer,
                                           width: Int, height: Int) throws -> [Float] {
        CVPixelBufferLockBaseAddress(buffer, .readOnly)
        defer { CVPixelBufferUnlockBaseAddress(buffer, .readOnly) }

        let bw = CVPixelBufferGetWidth(buffer)
        let bh = CVPixelBufferGetHeight(buffer)
        let stride = CVPixelBufferGetBytesPerRow(buffer)
        let format = CVPixelBufferGetPixelFormatType(buffer)
        guard let base = CVPixelBufferGetBaseAddress(buffer), bw > 0, bh > 0 else {
            throw Failure.couldNotRender
        }

        var out = [Float](repeating: 0, count: width * height)
        let bytes = base.assumingMemoryBound(to: UInt8.self)
        let floatsIn = base.assumingMemoryBound(to: Float.self)
        let isFloat = format == kCVPixelFormatType_OneComponent32Float

        for y in 0..<height {
            let sy = min(bh - 1, y * bh / max(height, 1))
            for x in 0..<width {
                let sx = min(bw - 1, x * bw / max(width, 1))
                let v: Float
                if isFloat {
                    v = floatsIn[(sy * stride / MemoryLayout<Float>.size) + sx]
                } else {
                    v = Float(bytes[sy * stride + sx]) / 255.0
                }
                out[y * width + x] = min(max(v, 0), 1)
            }
        }
        return out
    }
}
