#!/usr/bin/env python3
"""Write web/js/planet-maps.js: the planet maps in web/img/planets/ as data: URLs.

    ./tools/build-planet-maps.py

The landing page reads each map back out of a canvas to wrap it onto a sphere.
A page opened from file:// may not read back an image it loaded by URL, but it
may read a data: URL, so the maps travel inside a script and the planets look
the same from a file as from the site. Served gzipped, the base64 costs little.
"""
import base64
from pathlib import Path

WEB = Path(__file__).resolve().parent.parent / "web"
maps = {p.stem: "data:image/jpeg;base64," + base64.b64encode(p.read_bytes()).decode()
        for p in sorted((WEB / "img" / "planets").glob("*.jpg"))}
body = ",".join(f'{name}:"{url}"' for name, url in maps.items())
out = WEB / "js" / "planet-maps.js"
out.write_text("/* Generated by tools/build-planet-maps.py from web/img/planets/ (Solar System Scope, CC BY 4.0, see NOTICE). Do not edit. */\n"
               f"window.ORION_PLANET_MAPS={{{body}}};\n")
print(f"{out.name}: {', '.join(maps)}; {out.stat().st_size:,} bytes")
